nav:
  Home: /
#   About: /about/
  Writing: /archives/
  Projects: https://github.com/ericdouglas

projects_url: https://github.com/ericdouglas

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/ericdouglas
        twitter: https://twitter.com/ericdouglas_
        #facebook: /
        linkedin: https://br.linkedin.com/in/eric-douglas-81381282/en
    show_all_posts: true
    post_count: 5
    highlight: ir-black

# RSS
rss: atom.xml

# Plugins
plugins:
    disqus_shortname: ericdouglas
    google_analytics: UA-48165601-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
